### PR TITLE
[18.0][MIG] stock_packaging_calculator: Migration to 18.0

### PR DESCRIPTION
**Pull request by thienvh332**
### Ported PRs
- **#1407**
- **#1902**

### CODE REVIEW

**Review by simahawk — APPROVED** [review]
LGTM

**Comment by thienvh332** [comment]
Hi @simahawk , 
I'm sorry but I've closed this and created a new PR to merge into the OCA side. Could you come over there? ([Link here](https://github.com/OCA/stock-logistics-warehouse/pull/2173))

**Comment by simahawk** [comment]
@thienvh332 I thought I was already on OCA :rofl:

**Pull request closed without merging**
